# Generated by Django 5.1.1 on 2024-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('image', models.ImageField(default=None, null=True, upload_to='category_photo/', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='playground_photos/', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('cat', models.ManyToManyField(related_name='cat', to='SportsGrounds.category')),
                ('photo', models.ManyToManyField(related_name='Photo', to='SportsGrounds.photo')),
            ],
        ),
    ]
