# Generated by Django 5.1.1 on 2024-09-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsGrounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='Photo', to='SportsGrounds.photo'),
        ),
    ]
