# Generated by Django 5.1.1 on 2024-10-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsGrounds', '0002_alter_playground_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Вид спорта', 'verbose_name_plural': 'Виды спорта'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='playground',
            options={'ordering': ['name'], 'verbose_name': 'Спортивная площадка', 'verbose_name_plural': 'Спортивные площадки'},
        ),
        migrations.RemoveField(
            model_name='playground',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='playground',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='SportsGrounds.playground'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0),
        ),
        migrations.AlterField(
            model_name='playground',
            name='cat',
            field=models.ManyToManyField(related_name='cat', to='SportsGrounds.category', verbose_name='Площадки'),
        ),
    ]
