# Generated by Django 5.1.1 on 2024-10-04 15:28

import SportsGrounds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsGrounds', '0003_alter_category_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=SportsGrounds.models.get_upload_to, verbose_name='Фотография'),
        ),
    ]
